name: CI/CD Pipeline - Dev

on:
  push:
    branches:
     - dev

env:
  AWS_ACCOUNT: "708011889051"
  AWS_REGION: "us-east-1"
  APP_NAME: "linuxtips-app"
  CLUSTER_NAME: "linuxtips-ecs-cluster"
  REPOSITORY_NAME: "linuxtips/$APP_NAME"

jobs:
  ci-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Install GoLint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8

    - name: Lint App
      run: golangci-lint run ./... -E errcheck
      working-directory: ./app

    - name: Test App
      run: go test -v ./...
      working-directory: ./app